welcome_story_one = ("After a long journey you are exhausted but then you see a house in a clearing ahead!")
welcome_story_two = ("You are starving and tired. All that you want is somewhere to sit, eat and sleep!")
welcome_story_three = ("You go in, but as you do, you are confronted by three beasts!")
battle_question_one = ("Do you have what it takes to defeat these them?")
introduction_sequence = (welcome_story_one,welcome_story_two,welcome_story_three,battle_question_one)